version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    env_file: ".env"
    image: postgres:15.1-alpine
    container_name: demo-postgres-15.1
#    volumes:
##      - postgres_data:/var/lib/postgresql/data
#    command:
#      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  demo-web:
    env_file: ".env"
    build:
      dockerfile: Dockerfile
      context: .
    command: "./bin/rails server -b 0.0.0.0"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - GREEN_GROCER_DB_USERNAME=${GREEN_GROCER_DB_USERNAME}
      - GREEN_GROCER_DB_PASSWORD=${GREEN_GROCER_DB_PASSWORD}
    volumes:
      - .:/rails
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  postgres_data: {}
  app-storage: {}
